In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [5]:
df = pd.read_csv('balance-scale.csv',sep=',')
df.head()

class  left_weight  left_distance  right_weight  right_distance
0      1            1              1             1               1
1      2            1              1             1               2
2      2            1              1             1               3
3      2            1              1             1               4
4      2            1              1             1               5

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 625 entries, 0 to 624
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   class           625 non-null    int64
 1   left_weight     625 non-null    int64
 2   left_distance   625 non-null    int64
 3   right_weight    625 non-null    int64
 4   right_distance  625 non-null    int64
dtypes: int64(5)
memory usage: 24.5 KB


In [9]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
X=df.drop('class',axis=1)
y=df[['class']]

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [15]:
from sklearn.tree import DecisionTreeClassifier
clf_model = DecisionTreeClassifier(criterion='gini',random_state=42 , max_depth=3,min_samples_leaf=5)
clf_model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=3, min_samples_leaf=5, random_state=42)

In [16]:
y_pred = clf_model.predict(X_test)

In [20]:
from sklearn.metrics import confusion_matrix, classification_report

# Assuming y_test and y_pred are already defined
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


[[62  0 18]
 [ 8  0 10]
 [20  0 70]]
              precision    recall  f1-score   support

           0       0.69      0.78      0.73        80
           1       0.00      0.00      0.00        18
           2       0.71      0.78      0.74        90

    accuracy                           0.70       188
   macro avg       0.47      0.52      0.49       188
weighted avg       0.64      0.70      0.67       188



C:\Users\anuzk\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\anuzk\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\anuzk\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [22]:
target = list(df['class'].unique())
feature_names= list(X.columns)

In [27]:
from sklearn.tree import export_text
r = export_text(clf_model , feature_names=feature_names)
print(r)

|--- left_weight <= 2.50
|   |--- right_distance <= 1.50
|   |   |--- left_distance <= 2.50
|   |   |   |--- class: 2
|   |   |--- left_distance >  2.50
|   |   |   |--- class: 0
|   |--- right_distance >  1.50
|   |   |--- right_weight <= 2.50
|   |   |   |--- class: 2
|   |   |--- right_weight >  2.50
|   |   |   |--- class: 2
|--- left_weight >  2.50
|   |--- left_distance <= 2.50
|   |   |--- right_weight <= 2.50
|   |   |   |--- class: 0
|   |   |--- right_weight >  2.50
|   |   |   |--- class: 2
|   |--- left_distance >  2.50
|   |   |--- right_distance <= 3.50
|   |   |   |--- class: 0
|   |   |--- right_distance >  3.50
|   |   |   |--- class: 0

